version: "3"
services: 
  node:
    build: .
    command: "npm run start"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    expose: 
      - "3000"
    ports:
      - "3000:3000"